services:
  n8n:
    # 체berschreibt/erg채nzt nur Werte der Base
    environment:
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}

      # auf Postgres umstellen (falls nicht schon in Base)
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: change_me
      # DB_POSTGRESDB_SCHEMA: n8n
    depends_on:
      - postgres

  # Nur hinzuf체gen, wenn in der Base KEIN postgres-Service existiert:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: change_me
    volumes:
      - pg_data:/var/lib/postgresql/data
    # ports: ["5432:5432"]  # optional f체r lokale DB-Clients

  cloudflared:
    image: cloudflare/cloudflared:2024.8.2
    restart: unless-stopped
    depends_on:
      - n8n
    command: ["tunnel","--no-autoupdate","run","--token","${CLOUDFLARE_TUNNEL_TOKEN}"]

volumes:
  pg_data:
