services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    expose:
      - "5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_LOG_LEVEL=info
      - N8N_LOG_FORMAT=json
    volumes:
      - n8n_data:/home/node/.n8n
      - ../files:/files

volumes:
  n8n_data:
